import fs from 'node:fs';
import path from 'node:path';

const SOURCE_DIR = process.argv[2] || 'C:\\Users\\mcher\\Downloads\\Reels';
const projectRoot = process.cwd();
const targetDir = path.join(projectRoot, 'public', 'videos', 'reels');
const outputFile = path.join(projectRoot, 'src', 'app', 'data', 'generatedReels.ts');

const VIDEO_EXTENSIONS = new Set(['.mp4', '.mov', '.webm', '.m4v']);
const CATEGORY_POOL = ['accessories', 'beauty', 'fashion', 'lifestyle', 'wearables', 'home'];

const toSlug = (value) =>
  value
    .normalize('NFKD')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase();

const hashCode = (value) => {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) | 0;
  }
  return Math.abs(hash);
};

const tomanToRial = (toman) => toman * 10;

const getMarketPriceRial = (seed) => {
  const minToman = 3500000;
  const maxToman = 65000000;
  const step = 50000;
  const spread = Math.floor((maxToman - minToman) / step);
  const offset = seed % spread;
  const toman = minToman + offset * step;
  return tomanToRial(toman);
};

const getCategory = (filename) => {
  const lower = filename.toLowerCase();
  if (lower.includes('shoe') || lower.includes('sneaker')) return 'footwear';
  if (lower.includes('hair') || lower.includes('skin') || lower.includes('cream')) return 'beauty';
  if (lower.includes('watch') || lower.includes('smart')) return 'wearables';
  if (lower.includes('bag') || lower.includes('wallet')) return 'accessories';
  return CATEGORY_POOL[hashCode(lower) % CATEGORY_POOL.length];
};

if (!fs.existsSync(SOURCE_DIR)) {
  console.error(`Source directory does not exist: ${SOURCE_DIR}`);
  process.exit(1);
}

fs.mkdirSync(targetDir, { recursive: true });

const sourceFiles = fs
  .readdirSync(SOURCE_DIR, { withFileTypes: true })
  .filter((entry) => entry.isFile())
  .map((entry) => entry.name)
  .filter((file) => VIDEO_EXTENSIONS.has(path.extname(file).toLowerCase()))
  .sort((a, b) => a.localeCompare(b, 'en'));

const generatedProducts = [];
const generatedBaseVideos = [];
const generatedComments = {};

for (const fileName of sourceFiles) {
  const sourcePath = path.join(SOURCE_DIR, fileName);
  const targetPath = path.join(targetDir, fileName);
  fs.copyFileSync(sourcePath, targetPath);

  const stem = path.parse(fileName).name;
  const cleanedStem = stem
    .replace(/^savegram\.app[_-]?/i, '')
    .replace(/[_-]{2,}/g, '_')
    .trim();
  const rawSlug = toSlug(cleanedStem || stem) || `reel-${hashCode(fileName)}`;
  const shortSlug = rawSlug.slice(0, 24);
  const seed = hashCode(rawSlug);
  const hashSuffix = (seed % 0xffffff).toString(16).padStart(6, '0');
  const slug = `${shortSlug}-${hashSuffix}`;
  const productId = `gp-${slug}`;
  const videoId = `gv-${slug}`;
  const category = getCategory(fileName);

  const titleBase = cleanedStem.replace(/[_-]+/g, ' ').trim();
  const titleCore = titleBase.length > 0 ? titleBase : `Reel Product ${sourceFiles.indexOf(fileName) + 1}`;
  const title = titleCore.length > 52 ? `${titleCore.slice(0, 49)}...` : titleCore;

  generatedProducts.push({
    id: productId,
    category,
    name: title,
    price: getMarketPriceRial(seed),
    image: `https://picsum.photos/seed/product-${slug}/800/800`,
    description: `محصول ${title} با کیفیت مناسب و قیمت رقابتی برای بازار ایران.`,
    sizes: ['One Size'],
    colors: ['مشکی', 'سفید', 'نقره‌ای'],
    rating: 4 + (seed % 10) / 10,
    reviews: 120 + (seed % 700),
  });

  generatedBaseVideos.push({
    id: videoId,
    videoUrl: `/videos/reels/${fileName}`,
    thumbnail: `https://picsum.photos/seed/reel-${slug}/414/896`,
    username: `shop_${slug.slice(0, 10)}`,
    userAvatar: `https://picsum.photos/seed/avatar-${slug}/100/100`,
    likes: 1500 + (seed % 40000),
    comments: 30 + (seed % 700),
    shares: 10 + (seed % 200),
    description: `معرفی ${title} با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.`,
    hashtags: ['#خرید', '#محصول', '#فروش', `#${category}`],
    musicTitle: '',
    productId,
    isLive: false,
  });

  generatedComments[videoId] = [
    `این ${title} موجوده؟ قیمتش خیلی خوبه 👌`,
    `کیفیت ${title} در چه حدیه؟ کسی خریده؟`,
    `برای خرید ${title} ارسال فوری هم دارید؟`,
    `رنگ‌بندی ${title} کامل‌تر هم هست؟`,
    `به نظرم نسبت به بازار قیمت ${title} منطقیه 💸`,
  ];
}

const output = `/* Auto-generated by scripts/ingest-reels.mjs. Do not edit manually. */
import { Product, VideoFeed } from '../types';

export type GeneratedVideoSeed = Omit<VideoFeed, 'similarReels' | 'product'> & {
  productId: string;
};

export const generatedProducts: Product[] = ${JSON.stringify(generatedProducts, null, 2)};

export const generatedBaseVideos: GeneratedVideoSeed[] = ${JSON.stringify(generatedBaseVideos, null, 2)};

export const generatedReelCommentsFa: Record<string, string[]> = ${JSON.stringify(generatedComments, null, 2)};
`;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, output, 'utf8');

console.log(`Copied ${sourceFiles.length} videos into public/videos/reels`);
console.log(`Generated data file: ${outputFile}`);
