/* Auto-generated by scripts/ingest-reels.mjs. Do not edit manually. */
import { Product, VideoFeed } from '../types';

export type GeneratedVideoSeed = Omit<VideoFeed, 'similarReels' | 'product'> & {
  productId: string;
};

export const generatedProducts: Product[] = [
  {
    "id": "gp-aqmnhlwmydok4qhw-tm58aee-c4afcf",
    "category": "accessories",
    "name": "AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC...",
    "price": 406500000,
    "image": "https://picsum.photos/seed/product-aqmnhlwmydok4qhw-tm58aee-c4afcf/800/800",
    "description": "محصول AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC... با کیفیت مناسب و قیمت رقابتی برای بازار ایران.",
    "sizes": [
      "One Size"
    ],
    "colors": [
      "مشکی",
      "سفید",
      "نقره‌ای"
    ],
    "rating": 4.3,
    "reviews": 663
  },
  {
    "id": "gp-aqmtsdupemne5rre9nl4qv0r-916755",
    "category": "wearables",
    "name": "AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ...",
    "price": 426500000,
    "image": "https://picsum.photos/seed/product-aqmtsdupemne5rre9nl4qv0r-916755/800/800",
    "description": "محصول AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ... با کیفیت مناسب و قیمت رقابتی برای بازار ایران.",
    "sizes": [
      "One Size"
    ],
    "colors": [
      "مشکی",
      "سفید",
      "نقره‌ای"
    ],
    "rating": 4.3,
    "reviews": 613
  },
  {
    "id": "gp-aqnkeqmwe4y1x0y8exa0covz-416d31",
    "category": "home",
    "name": "AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg...",
    "price": 214000000,
    "image": "https://picsum.photos/seed/product-aqnkeqmwe4y1x0y8exa0covz-416d31/800/800",
    "description": "محصول AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg... با کیفیت مناسب و قیمت رقابتی برای بازار ایران.",
    "sizes": [
      "One Size"
    ],
    "colors": [
      "مشکی",
      "سفید",
      "نقره‌ای"
    ],
    "rating": 4.8,
    "reviews": 588
  },
  {
    "id": "gp-aqnncqgdgprt6qbzz-q6vxwy-1cbe7e",
    "category": "fashion",
    "name": "AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj...",
    "price": 102000000,
    "image": "https://picsum.photos/seed/product-aqnncqgdgprt6qbzz-q6vxwy-1cbe7e/800/800",
    "description": "محصول AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj... با کیفیت مناسب و قیمت رقابتی برای بازار ایران.",
    "sizes": [
      "One Size"
    ],
    "colors": [
      "مشکی",
      "سفید",
      "نقره‌ای"
    ],
    "rating": 4.4,
    "reviews": 614
  },
  {
    "id": "gp-aqonqljlvkpnzf35gv6bgc_l-f44949",
    "category": "beauty",
    "name": "AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ...",
    "price": 230000000,
    "image": "https://picsum.photos/seed/product-aqonqljlvkpnzf35gv6bgc_l-f44949/800/800",
    "description": "محصول AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ... با کیفیت مناسب و قیمت رقابتی برای بازار ایران.",
    "sizes": [
      "One Size"
    ],
    "colors": [
      "مشکی",
      "سفید",
      "نقره‌ای"
    ],
    "rating": 4,
    "reviews": 490
  },
  {
    "id": "gp-aqozgdfofpqucrb0hhk-cscp-a77081",
    "category": "wearables",
    "name": "AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03...",
    "price": 336500000,
    "image": "https://picsum.photos/seed/product-aqozgdfofpqucrb0hhk-cscp-a77081/800/800",
    "description": "محصول AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03... با کیفیت مناسب و قیمت رقابتی برای بازار ایران.",
    "sizes": [
      "One Size"
    ],
    "colors": [
      "مشکی",
      "سفید",
      "نقره‌ای"
    ],
    "rating": 4.3,
    "reviews": 653
  },
  {
    "id": "gp-aqpvipy3xh57cg-ueelcjdr8-e219a7",
    "category": "home",
    "name": "AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv...",
    "price": 589000000,
    "image": "https://picsum.photos/seed/product-aqpvipy3xh57cg-ueelcjdr8-e219a7/800/800",
    "description": "محصول AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv... با کیفیت مناسب و قیمت رقابتی برای بازار ایران.",
    "sizes": [
      "One Size"
    ],
    "colors": [
      "مشکی",
      "سفید",
      "نقره‌ای"
    ],
    "rating": 4.8,
    "reviews": 538
  }
];

export const generatedBaseVideos: GeneratedVideoSeed[] = [
  {
    "id": "gv-aqmnhlwmydok4qhw-tm58aee-c4afcf",
    "videoUrl": "/videos/reels/SaveGram.App_AQMNHLwMyDok4Qhw-TM58AEewKFOUhu_B1D67wAgDAdjA0xsCIg1ATikNVJEdrV2Fa4hSXUoiqofQ6INSRjixlbDI9pLRKBFRp0Vt4g.mp4",
    "thumbnail": "https://picsum.photos/seed/reel-aqmnhlwmydok4qhw-tm58aee-c4afcf/414/896",
    "username": "shop_aqmnhlwmyd",
    "userAvatar": "https://picsum.photos/seed/avatar-aqmnhlwmydok4qhw-tm58aee-c4afcf/100/100",
    "likes": 11043,
    "comments": 573,
    "shares": 153,
    "description": "معرفی AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC... با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.",
    "hashtags": [
      "#خرید",
      "#محصول",
      "#فروش",
      "#accessories"
    ],
    "musicTitle": "",
    "productId": "gp-aqmnhlwmydok4qhw-tm58aee-c4afcf",
    "isLive": false
  },
  {
    "id": "gv-aqmtsdupemne5rre9nl4qv0r-916755",
    "videoUrl": "/videos/reels/SaveGram.App_AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZruotxzMevR68co5QaA3XjAt0dGdTOViGkjQ4ZEFrwzsSb9n-TS7bpM.mp4",
    "thumbnail": "https://picsum.photos/seed/reel-aqmtsdupemne5rre9nl4qv0r-916755/414/896",
    "username": "shop_aqmtsdupem",
    "userAvatar": "https://picsum.photos/seed/avatar-aqmtsdupemne5rre9nl4qv0r-916755/100/100",
    "likes": 12693,
    "comments": 523,
    "shares": 203,
    "description": "معرفی AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ... با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.",
    "hashtags": [
      "#خرید",
      "#محصول",
      "#فروش",
      "#wearables"
    ],
    "musicTitle": "",
    "productId": "gp-aqmtsdupemne5rre9nl4qv0r-916755",
    "isLive": false
  },
  {
    "id": "gv-aqnkeqmwe4y1x0y8exa0covz-416d31",
    "videoUrl": "/videos/reels/SaveGram.App_AQNKEQMwE4y1x0Y8ExA0COVZ_mf4rDl_gPJKyHzXBYImN_CUgHhHZ5OGNi4G9gz9Eh_RPVMx6OgjaiIRatmTRgmQ1Bmyb8aju3Mm_ew.mp4",
    "thumbnail": "https://picsum.photos/seed/reel-aqnkeqmwe4y1x0y8exa0covz-416d31/414/896",
    "username": "shop_aqnkeqmwe4",
    "userAvatar": "https://picsum.photos/seed/avatar-aqnkeqmwe4y1x0y8exa0covz-416d31/100/100",
    "likes": 16868,
    "comments": 498,
    "shares": 178,
    "description": "معرفی AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg... با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.",
    "hashtags": [
      "#خرید",
      "#محصول",
      "#فروش",
      "#home"
    ],
    "musicTitle": "",
    "productId": "gp-aqnkeqmwe4y1x0y8exa0covz-416d31",
    "isLive": false
  },
  {
    "id": "gv-aqnncqgdgprt6qbzz-q6vxwy-1cbe7e",
    "videoUrl": "/videos/reels/SaveGram.App_AQNnCQGDGPRt6QBZZ-Q6vXwyWRpdWrD_GDnHX__jvtGv94sdwjzGkbBZ5Mmjzl2sS7ZQJ04nncSoL0ICd3_Nd8V0HlaWr6IvJfYmdDE.mp4",
    "thumbnail": "https://picsum.photos/seed/reel-aqnncqgdgprt6qbzz-q6vxwy-1cbe7e/414/896",
    "username": "shop_aqnncqgdgp",
    "userAvatar": "https://picsum.photos/seed/avatar-aqnncqgdgprt6qbzz-q6vxwy-1cbe7e/100/100",
    "likes": 31594,
    "comments": 524,
    "shares": 104,
    "description": "معرفی AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj... با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.",
    "hashtags": [
      "#خرید",
      "#محصول",
      "#فروش",
      "#fashion"
    ],
    "musicTitle": "",
    "productId": "gp-aqnncqgdgprt6qbzz-q6vxwy-1cbe7e",
    "isLive": false
  },
  {
    "id": "gv-aqonqljlvkpnzf35gv6bgc_l-f44949",
    "videoUrl": "/videos/reels/SaveGram.App_AQOnQLjlvkpnZF35gv6BGC_lLAxLKRAQpqSggae2sX5uOewy_rWcoF8Ip4xJ98bjCwEQ2BgSHHv1EdP9Bc9agebzVlgF7goIY44BlcQ.mp4",
    "thumbnail": "https://picsum.photos/seed/reel-aqonqljlvkpnzf35gv6bgc_l-f44949/414/896",
    "username": "shop_aqonqljlvk",
    "userAvatar": "https://picsum.photos/seed/avatar-aqonqljlvkpnzf35gv6bgc_l-f44949/100/100",
    "likes": 13570,
    "comments": 400,
    "shares": 80,
    "description": "معرفی AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ... با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.",
    "hashtags": [
      "#خرید",
      "#محصول",
      "#فروش",
      "#beauty"
    ],
    "musicTitle": "",
    "productId": "gp-aqonqljlvkpnzf35gv6bgc_l-f44949",
    "isLive": false
  },
  {
    "id": "gv-aqozgdfofpqucrb0hhk-cscp-a77081",
    "videoUrl": "/videos/reels/SaveGram.App_AQOzgDFofpQUCrb0hhK-Cscpf2195-InXtdLeCEzCCNztPV03XrLvg3-1iWdyOdyYI_DBZUA6UWXaB6wDg1u0HAaTrKhgB2JCLsPO2Y.mp4",
    "thumbnail": "https://picsum.photos/seed/reel-aqozgdfofpqucrb0hhk-cscp-a77081/414/896",
    "username": "shop_aqozgdfofp",
    "userAvatar": "https://picsum.photos/seed/avatar-aqozgdfofpqucrb0hhk-cscp-a77081/100/100",
    "likes": 32533,
    "comments": 563,
    "shares": 43,
    "description": "معرفی AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03... با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.",
    "hashtags": [
      "#خرید",
      "#محصول",
      "#فروش",
      "#wearables"
    ],
    "musicTitle": "",
    "productId": "gp-aqozgdfofpqucrb0hhk-cscp-a77081",
    "isLive": false
  },
  {
    "id": "gv-aqpvipy3xh57cg-ueelcjdr8-e219a7",
    "videoUrl": "/videos/reels/SaveGram.App_AQPvIPy3xH57cG-uEElCjdr8pPQQ-wIx91h2_x158mMTa2FVvA80R9rrB7_Hu4ff6PAcA4QwJW5MHrOKNascYSUv4L8ftjILKcOh-Y8.mp4",
    "thumbnail": "https://picsum.photos/seed/reel-aqpvipy3xh57cg-ueelcjdr8-e219a7/414/896",
    "username": "shop_aqpvipy3xh",
    "userAvatar": "https://picsum.photos/seed/avatar-aqpvipy3xh57cg-ueelcjdr8-e219a7/100/100",
    "likes": 13618,
    "comments": 448,
    "shares": 128,
    "description": "معرفی AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv... با بررسی قیمت، کیفیت و کاربرد در خرید روزمره.",
    "hashtags": [
      "#خرید",
      "#محصول",
      "#فروش",
      "#home"
    ],
    "musicTitle": "",
    "productId": "gp-aqpvipy3xh57cg-ueelcjdr8-e219a7",
    "isLive": false
  }
];

export const generatedReelCommentsFa: Record<string, string[]> = {
  "gv-aqmnhlwmydok4qhw-tm58aee-c4afcf": [
    "این AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC... موجوده؟ قیمتش خیلی خوبه 👌",
    "کیفیت AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC... در چه حدیه؟ کسی خریده؟",
    "برای خرید AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC... ارسال فوری هم دارید؟",
    "رنگ‌بندی AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC... کامل‌تر هم هست؟",
    "به نظرم نسبت به بازار قیمت AQMNHLwMyDok4Qhw TM58AEewKFOUhu B1D67wAgDAdjA0xsC... منطقیه 💸"
  ],
  "gv-aqmtsdupemne5rre9nl4qv0r-916755": [
    "این AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ... موجوده؟ قیمتش خیلی خوبه 👌",
    "کیفیت AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ... در چه حدیه؟ کسی خریده؟",
    "برای خرید AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ... ارسال فوری هم دارید؟",
    "رنگ‌بندی AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ... کامل‌تر هم هست؟",
    "به نظرم نسبت به بازار قیمت AQMtsdUPEMne5RrE9Nl4qV0RO97iOEWmMOo9hcTQHPgsa7SkZ... منطقیه 💸"
  ],
  "gv-aqnkeqmwe4y1x0y8exa0covz-416d31": [
    "این AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg... موجوده؟ قیمتش خیلی خوبه 👌",
    "کیفیت AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg... در چه حدیه؟ کسی خریده؟",
    "برای خرید AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg... ارسال فوری هم دارید؟",
    "رنگ‌بندی AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg... کامل‌تر هم هست؟",
    "به نظرم نسبت به بازار قیمت AQNKEQMwE4y1x0Y8ExA0COVZ mf4rDl gPJKyHzXBYImN CUg... منطقیه 💸"
  ],
  "gv-aqnncqgdgprt6qbzz-q6vxwy-1cbe7e": [
    "این AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj... موجوده؟ قیمتش خیلی خوبه 👌",
    "کیفیت AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj... در چه حدیه؟ کسی خریده؟",
    "برای خرید AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj... ارسال فوری هم دارید؟",
    "رنگ‌بندی AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj... کامل‌تر هم هست؟",
    "به نظرم نسبت به بازار قیمت AQNnCQGDGPRt6QBZZ Q6vXwyWRpdWrD GDnHX jvtGv94sdwj... منطقیه 💸"
  ],
  "gv-aqonqljlvkpnzf35gv6bgc_l-f44949": [
    "این AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ... موجوده؟ قیمتش خیلی خوبه 👌",
    "کیفیت AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ... در چه حدیه؟ کسی خریده؟",
    "برای خرید AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ... ارسال فوری هم دارید؟",
    "رنگ‌بندی AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ... کامل‌تر هم هست؟",
    "به نظرم نسبت به بازار قیمت AQOnQLjlvkpnZF35gv6BGC lLAxLKRAQpqSggae2sX5uOewy ... منطقیه 💸"
  ],
  "gv-aqozgdfofpqucrb0hhk-cscp-a77081": [
    "این AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03... موجوده؟ قیمتش خیلی خوبه 👌",
    "کیفیت AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03... در چه حدیه؟ کسی خریده؟",
    "برای خرید AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03... ارسال فوری هم دارید؟",
    "رنگ‌بندی AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03... کامل‌تر هم هست؟",
    "به نظرم نسبت به بازار قیمت AQOzgDFofpQUCrb0hhK Cscpf2195 InXtdLeCEzCCNztPV03... منطقیه 💸"
  ],
  "gv-aqpvipy3xh57cg-ueelcjdr8-e219a7": [
    "این AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv... موجوده؟ قیمتش خیلی خوبه 👌",
    "کیفیت AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv... در چه حدیه؟ کسی خریده؟",
    "برای خرید AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv... ارسال فوری هم دارید؟",
    "رنگ‌بندی AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv... کامل‌تر هم هست؟",
    "به نظرم نسبت به بازار قیمت AQPvIPy3xH57cG uEElCjdr8pPQQ wIx91h2 x158mMTa2FVv... منطقیه 💸"
  ]
};
