/* Auto-generated by scripts/ingest-profile-videos.mjs. Do not edit manually. */

export interface GeneratedProfileCreator {
  id: string;
  username: string;
  avatar: string;
}

export interface GeneratedProfileMediaReel {
  id: string;
  videoUrl: string;
  thumbnail: string;
  title: string;
  isIntro: boolean;
}

export interface GeneratedProfileMedia {
  username: string;
  introVideoUrl: string;
  introVideoName: string;
  reels: GeneratedProfileMediaReel[];
}

export const generatedProfileCreators: GeneratedProfileCreator[] = [
  {
    "id": "creator_59a5924d",
    "username": "اورال",
    "avatar": "/pics/avatars/avatar1.jpg"
  },
  {
    "id": "creator_5a4bb19",
    "username": "زیورآلات_گلیمی",
    "avatar": "/pics/avatars/avatar2.jpg"
  },
  {
    "id": "creator_4f5f7400",
    "username": "لوازم‌التحریر",
    "avatar": "/pics/avatars/avatar3.jpg"
  },
  {
    "id": "creator_58aac041",
    "username": "Creator-zizi",
    "avatar": "/pics/avatars/avatar4.jpg"
  },
  {
    "id": "creator_6f76f403",
    "username": "vendor-vestawatch",
    "avatar": "/pics/avatars/avatar1.jpg"
  }
];

export const generatedProfileMedia: GeneratedProfileMedia[] = [
  {
    "username": "اورال",
    "introVideoUrl": "/videos/profile/profile-59a5924d/clip-8-3db2def5.mp4",
    "introVideoName": "intro اُِوِرال • همیشه بپوش • • شروع سبکی نو ترکیبی ‘مدرن’ ‘کاربردی’ برای ‘ هر لحظه از روز و هرجا’ •",
    "reels": [
      {
        "id": "pv-profile-59a5924d-1",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-1-314bbd08.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-1",
        "title": "اُ ِوِرال ‘ کم جا ‘ سبک ترین لباسی که کامله 1,690 تومان در دو سایز سایز۲ تا سایز ۵۰جنس جین#",
        "isIntro": false
      },
      {
        "id": "pv-profile-59a5924d-2",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-2-6a513c25.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-2",
        "title": "اُِوِرال ‘ بی تا ‘ هم میشه تا کرد هم بدون تا 1,890 تومانمدل دمپا گشاد داره جنس جین چهارفصلبن",
        "isIntro": false
      },
      {
        "id": "pv-profile-59a5924d-3",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-3-75ac89dd.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-3",
        "title": "اُِوِرال 'کم‌جا' رنگی میتونه ترکیب رنگ تورو تعریف کنه؟ با کدوم رنگ؟ کم‌جای رنگ خودت رو انتخاب کن و با تمامی زیره‌هایی که داری استایل خودت رو بساز، از خونه تا خیابون. • جنس لینن ۱٫۲۹۰ برای دیدن جزئیات هایلایت و استوری رو م",
        "isIntro": false
      },
      {
        "id": "pv-profile-59a5924d-4",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-4-d1ea6a7.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-4",
        "title": "اُِوِرال •خُنک رنگ• برای تن هایی که نفس می کشن.رنگ های سبک، فرم های ساده، برای روز های گرمتو خنک",
        "isIntro": false
      },
      {
        "id": "pv-profile-59a5924d-5",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-5-7d9fcacb.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-5",
        "title": "اُِوِرال' کم‌جا ' سبک‌ترین لباسی که کامله 1,390 تومان در دو سایز جنس جین چهارفصل #اورال #overall #سرهمی #stylish #style #استایل",
        "isIntro": false
      },
      {
        "id": "pv-profile-59a5924d-6",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-6-2193a851.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-6",
        "title": "خبر خوب اینکه بعد از این همه درخواست که لباس های زیر اُِوِرال هم به سلیقه ی خودمون موجود کنیم مو",
        "isIntro": false
      },
      {
        "id": "pv-profile-59a5924d-7",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-7-588dbb05.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-7",
        "title": "وقتی استایلت صدای استقلالت باشه؛ این همان چیزی‌ست که جامپسوییت مستقل روایت میکند • جنس کتان • 1,390 تومان • تا سایز ۴۲",
        "isIntro": false
      },
      {
        "id": "pv-profile-59a5924d-8",
        "videoUrl": "/videos/profile/profile-59a5924d/clip-8-3db2def5.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-59a5924d-8",
        "title": "intro اُِوِرال • همیشه بپوش • • شروع سبکی نو ترکیبی ‘مدرن’ ‘کاربردی’ برای ‘ هر لحظه از روز و هرجا’ •",
        "isIntro": true
      }
    ]
  },
  {
    "username": "زیورآلات_گلیمی",
    "introVideoUrl": "/videos/profile/profile-71260a3a/clip-8-6a5a83b0.mp4",
    "introVideoName": "intro یونا 🌱✨یه جمله یا کلمه بخواید برای یونا بگید چی می گید؟ 😍.تمام تلاشمون این هست که کار باکیفیت",
    "reels": [
      {
        "id": "pv-profile-71260a3a-1",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-1-1ea39826.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-1",
        "title": "نتیجه کار؛ آخر ویدیو 🥰✨کمربند جدید یونا به اسم موج 🌊پروسه تولید یه محصول خیلی طول میکشهاز طر",
        "isIntro": false
      },
      {
        "id": "pv-profile-71260a3a-2",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-2-2ff35a04.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-2",
        "title": "بند دوربین گلیمی یونا 📷به اسم شیراز 💙 ● طول ۱۲۰ سانتی متر● چرم طبیعی (گاوی)● تحمل وزن دوربینها",
        "isIntro": false
      },
      {
        "id": "pv-profile-71260a3a-3",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-3-6e92c065.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-3",
        "title": "جایی که چرم و گلیم یکی می شن 🤍۱۸ ثانیه از مراحل چرم زدن بند دوربینمون 🥰برای استحکام و ماندگاری",
        "isIntro": false
      },
      {
        "id": "pv-profile-71260a3a-4",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-4-70ca7711.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-4",
        "title": "دست سازه ای از دل نخ و چرم 🧵✨️اسم این جاکلیدی افق هست.محکم و بادوامه، چرم طبیعی استفاده می شه ق",
        "isIntro": false
      },
      {
        "id": "pv-profile-71260a3a-5",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-5-77d1114d.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-5",
        "title": "دستبند گندم 🌾🌿از مرحله ی بافت تا جزئیات نهایی ✨کاملاً دست بافه و پشتش با دکمه بسته میشه 🤍میتو",
        "isIntro": false
      },
      {
        "id": "pv-profile-71260a3a-6",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-6-2441a97c.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-6",
        "title": "قطعا ایرانی ترین طرح و ترکیب رنگ یونا همین طرح مهتاب هست که طی سالها هنوز که هنوز پرطرفدار هس",
        "isIntro": false
      },
      {
        "id": "pv-profile-71260a3a-7",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-7-4f30c372.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-7",
        "title": "کمربند غروب 🌅یکی از کمربندهای جذاب یونا 😍مشخصاتش ● گلیم این کمربند از بهترین نوع کاموای موجود",
        "isIntro": false
      },
      {
        "id": "pv-profile-71260a3a-8",
        "videoUrl": "/videos/profile/profile-71260a3a/clip-8-6a5a83b0.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-71260a3a-8",
        "title": "intro یونا 🌱✨یه جمله یا کلمه بخواید برای یونا بگید چی می گید؟ 😍.تمام تلاشمون این هست که کار باکیفیت",
        "isIntro": true
      }
    ]
  },
  {
    "username": "لوازم‌التحریر",
    "introVideoUrl": "/videos/profile/profile-4f5f7400/clip-8-554935d1.mp4",
    "introVideoName": "intro واقعا چیشد که کارمند نشدم 😂همه محصولاتی که داخل پیج میبینید حاصل ۳ سال زحمته شبانه روزیه که کنا",
    "reels": [
      {
        "id": "pv-profile-4f5f7400-1",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-1-466f8918.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-1",
        "title": "اجازه بدیدتشکر کنم که همیشه منو مدیون خودتون می کنیداز بس که مهربونم و قشنگیدخواستم بگم پوشه ها",
        "isIntro": false
      },
      {
        "id": "pv-profile-4f5f7400-2",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-2-123108c3.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-2",
        "title": "این زیرو فقط آشناها بخونن❌نوت بینهایت 🫶• جنس جلدش کاملا چرمیه• ۱۵۰ برگ ظرفیت کاغذ ۸۰ گرمی داره",
        "isIntro": false
      },
      {
        "id": "pv-profile-4f5f7400-3",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-3-325e00e5.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-3",
        "title": "این زیرو فقط نخونهمه اطلاعات کلاسورو این زیر برات نوشتم این محصول اولین بار توسط بُن بوک در ایرا",
        "isIntro": false
      },
      {
        "id": "pv-profile-4f5f7400-4",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-4-3790de85.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-4",
        "title": "بفرست برای کسی که بهش نیاز داره ❌پنج تا رنگ خوشگل داره مشکی ، بنفش ، آبی ، صورتی ، سبز 🌸بیا ت",
        "isIntro": false
      },
      {
        "id": "pv-profile-4f5f7400-5",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-5-32e68bb5.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-5",
        "title": "دختر پسرای دانشگاه🫦باید اینجوری باشن🤌این کلاسورا با یه پک تخفیفی قراره ۱۱ شهریور بره روسایتاگر",
        "isIntro": false
      },
      {
        "id": "pv-profile-4f5f7400-6",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-6-3bdbe2e1.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-6",
        "title": "منم باورم نمیشد !!پوشه ها برای اولین بار تو ایران توسط تیم بن طراحی و ساخته شده 🤌• یه فضای بزرگ",
        "isIntro": false
      },
      {
        "id": "pv-profile-4f5f7400-7",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-7-39fe067b.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-7",
        "title": "می خوام تو ده ثانیه ثابت کنمشاید نتونم یه کبریت روشن کنماما کار دیگه ای از دستم بر میاد 🖐🏻کلاس",
        "isIntro": false
      },
      {
        "id": "pv-profile-4f5f7400-8",
        "videoUrl": "/videos/profile/profile-4f5f7400/clip-8-554935d1.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-4f5f7400-8",
        "title": "intro واقعا چیشد که کارمند نشدم 😂همه محصولاتی که داخل پیج میبینید حاصل ۳ سال زحمته شبانه روزیه که کنا",
        "isIntro": true
      }
    ]
  },
  {
    "username": "Creator-zizi",
    "introVideoUrl": "/videos/profile/profile-58aac041/clip-1-87b820b.mp4",
    "introVideoName": "پنج تا گجتی که تازگیا خریدم و واقعا ازشون راضیم!😊تا هنوز فرصت هست از تکنوپی اعتبارت رو بگیر",
    "reels": [
      {
        "id": "pv-profile-58aac041-1",
        "videoUrl": "/videos/profile/profile-58aac041/clip-1-87b820b.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-58aac041-1",
        "title": "پنج تا گجتی که تازگیا خریدم و واقعا ازشون راضیم!😊تا هنوز فرصت هست از تکنوپی اعتبارت رو بگیر",
        "isIntro": false
      },
      {
        "id": "pv-profile-58aac041-2",
        "videoUrl": "/videos/profile/profile-58aac041/clip-2-6e9347e.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-58aac041-2",
        "title": "سال ها ساعت هوشمند داشتم…ولی اآان؟ همه شون عقربه ای شدن.تو ایران ساعت عقربه ای خواستی… @vesta.",
        "isIntro": false
      },
      {
        "id": "pv-profile-58aac041-3",
        "videoUrl": "/videos/profile/profile-58aac041/clip-3-34fa4c73.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-58aac041-3",
        "title": "فکر نمیکردم اینقد خوشحال شم 🥹▫️امروز کل تهران رو میخواستم بچرخم باهاش 😂 خیلی ذوقشو دارم 😍#اسک",
        "isIntro": false
      },
      {
        "id": "pv-profile-58aac041-4",
        "videoUrl": "/videos/profile/profile-58aac041/clip-4-f7bab61.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-58aac041-4",
        "title": "میکروفون های Hollyland رو می تونی از دیجی صدا با گارانتی دو ساله بخری🎤@digi.seda😇تو هر بازه قی",
        "isIntro": false
      },
      {
        "id": "pv-profile-58aac041-5",
        "videoUrl": "/videos/profile/profile-58aac041/clip-5-6481a0a9.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-58aac041-5",
        "title": "یه بند پارچه ایه … اما خواب منو نجات داد 🥹◽️ببین Whoop همون چیزیه که هر روز صبح بهم میگه بدنم چ",
        "isIntro": false
      },
      {
        "id": "pv-profile-58aac041-6",
        "videoUrl": "/videos/profile/profile-58aac041/clip-6-9aefb6.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-58aac041-6",
        "title": "یه ساعت کوچیک روی دستت، ولی کلی کار می کنه ⌚️😎✅ جواب دادن تماس تو خیابون شلوغ✅ چک کردن پیام وسط",
        "isIntro": false
      }
    ]
  },
  {
    "username": "vendor-vestawatch",
    "introVideoUrl": "/videos/profile/profile-6f76f403/clip-7-5ebfaca5.mp4",
    "introVideoName": "intro حرفی باقی می مونه؟ «سواچ» رو کامنت کن و..👇🏻یادت نره این تنوع سواچ رو در هیچ جای ایران پیدا ن",
    "reels": [
      {
        "id": "pv-profile-6f76f403-1",
        "videoUrl": "/videos/profile/profile-6f76f403/clip-1-165009b3.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-6f76f403-1",
        "title": "«چرخ و فلک» رو کامنت کردی؟🎡🎠🎪🎢 🥲توی هایلایت سواچ، ساعت های جدیدش منتظرتن🙂 ↔️🇨🇭موومنت کوا",
        "isIntro": false
      },
      {
        "id": "pv-profile-6f76f403-2",
        "videoUrl": "/videos/profile/profile-6f76f403/clip-2-5a1b0d88.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-6f76f403-2",
        "title": "«ساحل» رو یادت نره! 🏖️🇸🇪🇯🇵برند تریوا سوئدی، موومنت کوارتز ژاپنی🪢بند برزنتی🪙قاب ۳۷ میلیمتر",
        "isIntro": false
      },
      {
        "id": "pv-profile-6f76f403-3",
        "videoUrl": "/videos/profile/profile-6f76f403/clip-3-2d5d677d.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-6f76f403-3",
        "title": "«سایه» یادت نره 😎🇯🇵🇮🇹برند ایتالیایی، موومنت کوارتز سیکو🪙قاب ۴۲میلی متری پلی کربنات💎کریستا",
        "isIntro": false
      },
      {
        "id": "pv-profile-6f76f403-4",
        "videoUrl": "/videos/profile/profile-6f76f403/clip-4-26a7373e.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-6f76f403-4",
        "title": "«شفاف» رو کامنت کردی؟🥽 🥲توی هایلایت سواچ، ساعت های جدیدش منتظرتن🙂 ↔️🇨🇭موومنت کوارتز سوییس🙋",
        "isIntro": false
      },
      {
        "id": "pv-profile-6f76f403-5",
        "videoUrl": "/videos/profile/profile-6f76f403/clip-5-178a0df8.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-6f76f403-5",
        "title": "«مینیمال ترین»تر از این؟!😱🇩🇰🇯🇵برند دانمارکی پیکتو، موومنت کوارتز ژاپنی🪢بند برزنتی از جنس پ",
        "isIntro": false
      },
      {
        "id": "pv-profile-6f76f403-6",
        "videoUrl": "/videos/profile/profile-6f76f403/clip-6-7ec398ce.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-6f76f403-6",
        "title": "«نانو» رو کامنت کن و مشخصاتش رو اینجا بخون👇💍 قاب ۲۳ میلیمتری🛡 ضدضربه 🌊 مقاومت در برابر آب تا",
        "isIntro": false
      },
      {
        "id": "pv-profile-6f76f403-7",
        "videoUrl": "/videos/profile/profile-6f76f403/clip-7-5ebfaca5.mp4",
        "thumbnail": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=414&h=736&fit=crop&seed=profile-6f76f403-7",
        "title": "intro حرفی باقی می مونه؟ «سواچ» رو کامنت کن و..👇🏻یادت نره این تنوع سواچ رو در هیچ جای ایران پیدا ن",
        "isIntro": true
      }
    ]
  }
];
